name: PuppyVet
main: com.inrevo.puppyvet.Main
version: 1.0
commands:
   calm:
      description: calms dogs/wolves, stop them being angry and growling.
      usage: /calm [radius] (default 10)
      permission: puppyvet.calm
      permission-message: You don't have permission to calm wolves or dogs
   packhere:
      description: Finds all your wolves in loaded chunks of current world and teleports them to you
      usage: /packhere
      permission: puppyvet.packhere
      permission-message: You don't have permission to move your pack
   whosepack:
      description: Tells you who owns the dogs within [radius]
      usage: /packhere [radius] (default 10)
      permission: puppyvet.whosepack
      permission-message: You don't have permission to sniff dogs to find who feeds them                    